# Generated by Django 5.1.7 on 2025-04-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='student_rollno',
            new_name='package_no',
        ),
    ]
